### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by harshguptahg007**
This is a solved program for Highest Common Factor using Java

### CODE REVIEW

**Review by G1Joshi — COMMENTED** [review]
put your file in ```Java``` folder

**Review by G1Joshi — CHANGES_REQUESTED** [review]
after putting your file in ```Java``` folder, create a pull request

**Comment by harshguptahg007** [comment]
@G1Joshi ok.

**Comment by harshguptahg007** [comment]
@G1Joshi I have done the requested changes. Are there any more changes you want me to do?

**Pull request closed without merging**
