### PR TITLE
Maximum number of handshakes in kotlin

### PR DESCRIPTION
**Pull request by tushar2407**

### CODE REVIEW

**Comment by tushar2407** [comment]
Hi @G1Joshi,
There are a lot of files which even though the same are added in my commit. Is there a problem at my end?
Ps. I did not touch any file except my own.
Thanks

**Comment by G1Joshi** [comment]
@tushar2407 you just have to add your file and don't remove other files.

**Comment by tushar2407** [comment]
@G1Joshi 
Yes, I didn't do anything to any other file at all.
But how do I fix that now?
Delete this branch and make a new PR or this works?

**Comment by G1Joshi** [comment]
@tushar2407 create a new branch, add commits then create a pull request and make sure that on master branch everything is up to date.

**Comment by tushar2407** [comment]
@G1Joshi 
image
I am getting this error and when reset head command is put then it deletes a lot of different files. So could you please assist me as to how to start working on your repo?
Thanks

**Pull request closed without merging**
