### PR TITLE
create_simran29aw_sum_of_digits.cpp

### PR DESCRIPTION
**Pull request by simran29aw**

### CODE REVIEW

**Review by G1Joshi — CHANGES_REQUESTED** [review]
@simran29aw add username as well as file extension

**Review by G1Joshi — CHANGES_REQUESTED** [review]
@simran29aw add proper extension to the file

**Review by simran29aw — COMMENTED** [review]
changes are made

**Comment by simran29aw** [comment]
changes made

**Review by G1Joshi — APPROVED** [review]

**Pull request merged**
