### PR TITLE
Create find_second_largest_number.sh

### PR DESCRIPTION
**Pull request by funwaa**
Script can find the Nth largest or smallest number within a list of numbers (file)

### CODE REVIEW

**Review by joe733 — CHANGES_REQUESTED** [review]
The variables are initialized without space like: `var_name=` instead of `var_name =`

It's causing this error:
```
./2nd_lgst.sh: line 5: listfile: command not found
./2nd_lgst.sh: line 6: type: =: not found
./2nd_lgst.sh: line 6: type: largest: not found
./2nd_lgst.sh: line 7: nth: command not found
Unknown type.
```

The program gives wrong output:
image

**Review by funwaa — COMMENTED** [review]
Fixed variable definitions

**Comment by funwaa** [comment]
> The variables are initialized without space like: `var_name=` instead of `var_name =`

That's what happens when you do Ruby for a long time... My bad, fixed the mistakes. Should run fine now.

**Review by G1Joshi — APPROVED** [review]

**Comment by G1Joshi** [comment]
Welcome to the world of C0D1NG 🚀

**Pull request merged**
